public class DMD_Class_ContactUtils {

    public static void create(){
        Contact a = new Contact(LastName='David Marquez');
		insert a;
    }
    
    /** DUMMY THINGS (NOT TESTED) **/
    public static void dummyMethod(){
        System.debug('Dummy method never tested');
    }
    
    public static void dummyMethod2(){
        System.debug('Dummy method never tested');
    }
    
    public static void dummyMethod3(){
        System.debug('Dummy method never tested');
    }
    
    public static void dummyMethod4(){
        System.debug('Dummy method never tested');
    }
    
    public static void dummyMethod5(){
        System.debug('Dummy method never tested');
    }
}